In [1]:
import pandas as pd
import numpy as ny
import matplotlib.pyplot as plt


In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.astype(int)

In [5]:
dataset

age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]


In [8]:
independent

age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [9]:
dependent=dataset[['charges']]


In [10]:
dependent

charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent, dependent,test_size=0.30, random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [13]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=100, max_features='log2')
regressor.fit(x_train,y_train)

C:\Users\Evangeline\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor(max_features='log2')

In [14]:
x_train

array([[-1.5330973 , -0.36100765, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.278355  , -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.51612426,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.84052963, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.75787698, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.95941426, -0.06746417, -0.97676557, -0.50466988]])

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent, dependent,test_size=0.30, random_state=0)

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [17]:
x_train

array([[-1.5330973 , -0.36100765, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.278355  , -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.51612426,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.84052963, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.75787698, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.95941426, -0.06746417, -0.97676557, -0.50466988]])

In [18]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor()
regressor=regressor.fit(x_train,y_train)


C:\Users\Evangeline\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


In [19]:
x_train

array([[-1.5330973 , -0.36100765, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.278355  , -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.51612426,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.84052963, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.75787698, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.95941426, -0.06746417, -0.97676557, -0.50466988]])

In [26]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid={'criterion':['absolute_error', 'friedman_mse', 'poisson'], 'max_features': ['sqrt', 'log2', 'None'], 'n_estimators':[100]}

In [27]:
grid= GridSearchCV(RandomForestRegressor(),param_grid, refit= True, verbose=3, n_jobs=-1 )

In [28]:
grid.fit(x_train, y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits


C:\Users\Evangeline\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
15 fits failed out of a total of 45.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Evangeline\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Evangeline\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Evangeline\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Evangeline\ana

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['absolute_error', 'friedman_mse',
                                       'poisson'],
                         'max_features': ['sqrt', 'log2', 'None'],
                         'n_estimators': [100]},
             verbose=3)

In [29]:
re=grid.cv_results_

In [30]:
table=pd.DataFrame.from_dict(re)

In [31]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.928614      0.145022         0.018749        0.015307   
1       0.920468      0.090669         0.012499        0.006249   
2       0.000000      0.000000         0.000000        0.000000   
3       0.434255      0.062205         0.012500        0.006250   
4       0.368330      0.065085         0.012578        0.011819   
5       0.000000      0.000000         0.000000        0.000000   
6       0.328394      0.011586         0.012499        0.006249   
7       0.300231      0.015379         0.009411        0.007684   
8       0.000000      0.000000         0.000000        0.000000   

  param_criterion param_max_features param_n_estimators  \
0  absolute_error               sqrt                100   
1  absolute_error               log2                100   
2  absolute_error               None                100   
3    friedman_mse               sqrt                100   
4    friedman_mse               log2                100   
5    friedman_mse               None                100   
6         poisson               sqrt                100   
7         poisson               log2                100   
8         poisson               None                100   

                                              params  split0_test_score  \
0  {'criterion': 'absolute_error', 'max_features'...           0.859872   
1  {'criterion': 'absolute_error', 'max_features'...           0.863937   
2  {'criterion': 'absolute_error', 'max_features'...                NaN   
3  {'criterion': 'friedman_mse', 'max_features': ...           0.862896   
4  {'criterion': 'friedman_mse', 'max_features': ...           0.863899   
5  {'criterion': 'friedman_mse', 'max_features': ...                NaN   
6  {'criterion': 'poisson', 'max_features': 'sqrt...           0.857521   
7  {'criterion': 'poisson', 'max_features': 'log2...           0.858185   
8  {'criterion': 'poisson', 'max_features': 'None...                NaN   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.799348           0.806892           0.820669           0.773009   
1           0.799543           0.809464           0.816620           0.771509   
2                NaN                NaN                NaN                NaN   
3           0.790160           0.799586           0.815594           0.777955   
4           0.787274           0.798041           0.825051           0.773812   
5                NaN                NaN                NaN                NaN   
6           0.791556           0.798008           0.819500           0.774758   
7           0.792145           0.800745           0.822849           0.774088   
8                NaN                NaN                NaN                NaN   

   mean_test_score  std_test_score  rank_test_score  
0         0.811958        0.028542                2  
1         0.812215        0.030066                1  
2              NaN             NaN                7  
3         0.809238        0.029514                5  
4         0.809615        0.031937                3  
5              NaN             NaN                7  
6         0.808269        0.028494                6  
7         0.809603        0.028915                4  
8              NaN             NaN                7

In [32]:
age_input=float(input("Age: "))
bmi_input=float(input("BMI: "))
children_input=float(input("Children: "))
sex_male_input=int(input("Sex Male 0 or 1: "))
smoker_yes_input=int(input("Smoker yes o or 1: "))

Age: 42
BMI: 28
Children: 2
Sex Male 0 or 1: 0
Smoker yes o or 1: 0


In [33]:
Future_Prediction=grid.predict([[age_input,bmi_input, children_input,sex_male_input, smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[15772.05]
